using System;

namespace Nop.Plugin.Misc.SyncCatalog.Areas.Admin.Models.Sync
{
    public class ProductSync
    {
        public int product_type_id { get; set; }
        public int parent_grouped_product_id { get; set; }
        public bool visible_individually { get; set; }
        public string name { get; set; }
        public string short_description { get; set; }
        public string full_description { get; set; }
        public string admin_comment { get; set; }
        public int product_template_id { get; set; }
        public int vendor_id { get; set; }
        public bool show_on_homepage { get; set; }
        public string meta_keywords { get; set; }
        public string meta_description { get; set; }
        public string meta_title { get; set; }
        public bool allow_customer_reviews { get; set; }
        public int approved_rating_sum { get; set; }
        public int not_approved_rating_sum { get; set; }
        public int approved_total_reviews { get; set; }
        public int not_approved_total_reviews { get; set; }
        public bool subject_to_acl { get; set; }
        public bool limited_to_stores { get; set; }
        public string sku { get; set; }
        public string manufacturer_part_number { get; set; }
        public string gtin { get; set; }
        public bool is_gift_card { get; set; }
        public int gift_card_type_id { get; set; }
        public int overridden_gift_card_amount { get; set; }
        public bool require_other_products { get; set; }
        public string required_product_ids { get; set; }
        public bool automatically_add_required_products { get; set; }
        public bool is_download { get; set; }
        public int download_id { get; set; }
        public bool unlimited_downloads { get; set; }
        public int max_number_of_downloads { get; set; }
        public int download_expiration_days { get; set; }
        public int download_activation_type_id { get; set; }
        public bool has_sample_download { get; set; }
        public int sample_download_id { get; set; }
        public bool has_user_agreement { get; set; }
        public string user_agreement_text { get; set; }
        public bool is_recurring { get; set; }
        public int recurring_cycle_length { get; set; }
        public int recurring_cycle_period_id { get; set; }
        public int recurring_total_cycles { get; set; }
        public bool is_rental { get; set; }
        public int rental_price_length { get; set; }
        public int rental_price_period_id { get; set; }
        public bool is_ship_enabled { get; set; }
        public bool is_free_shipping { get; set; }
        public bool ship_separately { get; set; }
        public int additional_shipping_charge { get; set; }
        public int delivery_date_id { get; set; }
        public bool is_tax_exempt { get; set; }
        public int tax_category_id { get; set; }
        public bool is_telecommunications_or_broadcasting_or_electronic_services { get; set; }
        public int manage_inventory_method_id { get; set; }
        public int product_availability_range_id { get; set; }
        public bool use_multiple_warehouses { get; set; }
        public int warehouse_id { get; set; }
        public int stock_quantity { get; set; }
        public bool display_stock_availability { get; set; }
        public bool display_stock_quantity { get; set; }
        public int min_stock_quantity { get; set; }
        public int low_stock_activity_id { get; set; }
        public int notify_admin_for_quantity_below { get; set; }
        public int backorder_mode_id { get; set; }
        public bool allow_back_in_stock_subscriptions { get; set; }
        public int order_minimum_quantity { get; set; }
        public int order_maximum_quantity { get; set; }
        public string allowed_quantities { get; set; }
        public bool allow_adding_only_existing_attribute_combinations { get; set; }
        public bool not_returnable { get; set; }
        public bool disable_buy_button { get; set; }
        public bool disable_wishlist_button { get; set; }
        public bool available_for_pre_order { get; set; }
        public object pre_order_availability_start_date_time_utc { get; set; }
        public bool call_for_price { get; set; }
        public decimal price { get; set; }
        public float old_price { get; set; }
        public decimal product_cost { get; set; }
        public bool customer_enters_price { get; set; }
        public int minimum_customer_entered_price { get; set; }
        public int maximum_customer_entered_price { get; set; }
        public bool baseprice_enabled { get; set; }
        public int baseprice_amount { get; set; }
        public int baseprice_unit_id { get; set; }
        public int baseprice_base_amount { get; set; }
        public int baseprice_base_unit_id { get; set; }
        public bool mark_as_new { get; set; }
        public object mark_as_new_start_date_time_utc { get; set; }
        public object mark_as_new_end_date_time_utc { get; set; }
        public bool has_tier_prices { get; set; }
        public bool has_discounts_applied { get; set; }
        public float weight { get; set; }
        public int length { get; set; }
        public int width { get; set; }
        public int height { get; set; }
        public object available_start_date_time_utc { get; set; }
        public object available_end_date_time_utc { get; set; }
        public int display_order { get; set; }
        public bool published { get; set; }
        public bool deleted { get; set; }
        public DateTime created_on_utc { get; set; }
        public DateTime updated_on_utc { get; set; }
        public int id { get; set; }
    }
}
